language: node_js

node_js:
  - "4.1"

script:
  - ./node_modules/karma/bin/karma start karma.conf.js

before_script:
  - npm install -g bower
  - npm install
  - bower install

cache:
  directories:
    - node_modules
    - bower_components

addons:
    code_climate:
        repo_token: 0eeb31c46e6765ec322c24e8af2b05701a19a78f2f6eca5e27a9eb2fe0c93ec6
